---
package: 
  package: 
    - .htaccess
    - index.php
    - bit_setup_inc.php
  type:
    - edit_type.php
    - list_type.php
    - remove_type.php
    - lookup_type_inc.php
    - TypeClass.php
  service:
    - ServiceClass.php
package/templates: 
  package: 
    - menu_package.tpl
    - admin_package.tpl
    - menu_package_admin.tpl
  type:
    - display_index.tpl
    - display_type.tpl
    - edit_type.tpl
    - list_type.tpl
package/admin: 
  package: 
    - admin_package_inc.php
    - schema.yaml
package/scripts:
  type:
    - TypeClass.js
package/icons: 
  copy: 
    - pkg_package.png
