---
plugin: 
  plugin:
    - PluginClass.php
    - plugin_inc.php
    - admin_plugin_inc.php
    - schema_plugin.yaml
plugin/templates:
  plugin:
    - service_admin_inc.tpl
    - menu_plugin_admin_inc.tpl
    - service_edit_tab_inc.tpl
    - service_edit_mini_inc.tpl
  section:
    - service_display_section.tpl
    - display_section_inc.tpl
    - edit_section_inc.tpl
    - menu_plugin_inc.tpl
